project/Cliente/urls.py
from django.urls import path
from . import views



app_name = "Cliente"

urlpatterns = [
    path("", views.view_Cliente, name = "Cliente"),
    path("usuario_buscado/", views.view_usuario_buscado, name="usuario_buscado"),
    path("crear_usuarios/", views.Formulario_usuarios, name="crear_usuarios"),
    path("mostrar_usuario_filtrado/", views.view_usuario_buscado, name="filtro_usuario"),
    path("login/", views.view_login, name="login"),
    path("logout/", views.view_logout, name="logout"),
    path("avatar/", views.crear_avatar_view, name="avatar"),
    path("editar_usuario/", views.editar_perfil_view, name="editarusuario"),
    path("eliminar_comentario/<id>", views.eliminar_comentario,name="borrarcomentario"),
    path("editar_comentario/<pk>", views.ComentarioUpdateView.as_view(), name="editarcomentario"),
    path("eleccion_comentario/<id>", views.editar_comentario, name="eleccioncomentario"),
]

project/MainM/urls.py
from django.urls import path
from . import views

app_name = "MainM"

urlpatterns = [
    path("", views.view_mainmenu, name = "MainM"),
    path("Redes/", views.view_about, name = "Redes"),
]

project/Producto/urls.py
from django.urls import path
from . import views

app_name = "Producto"

urlpatterns = [
    path("", views.view_Producto, name = "Producto"),
    path("comentar/", views.comentar_view, name="comentar"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("MainM.urls")),
    path("Cliente/", include("Cliente.urls")),
    path("Producto/", include("Producto.urls")),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/Cliente/models.py
from django.db import models
from django.contrib.auth.models import User

 

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(default="avatares/avatar_predeterminado.webp", upload_to='avatares/', null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"


class Videos(models.Model):
    video = models.FileField(upload_to="videos/", null=True, blank=True)
    titulo = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.titulo}"


class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.CharField(max_length=2200)
    post = models.ForeignKey(Videos, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.autor}: '{self.post}'"

project/Cliente/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserModel
from . import models    
class BuscarUsuarioForm(forms.Form):
    username = forms.CharField(label='Nombre de usuario', max_length=100)
        
        
class CrearUsuarioForm(UserCreationForm):
    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir Contraseña", widget=forms.PasswordInput)
    fecha_nacimiento = forms.DateField()
    
    class Meta:
        model = UserModel
        fields = ["email","password1","password2","username","first_name","last_name","username"]
        
class UserEditionFormulario(UserChangeForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    nombre = forms.CharField(label="Nombre")
    apellido = forms.CharField(label="Apellido")
    class Meta:
        model = UserModel
        fields = ["email", "password1", "password2", "nombre", "apellido",]
        exclude = ["contraseña"]

        
class UserAvatarFormulario(forms.ModelForm):

    class Meta:
        model = models.Avatar
        fields = ["imagen"]
        
        
class Comentarform(forms.ModelForm):
    class Meta:
        model = models.Comentario
        fields = ["texto","post"]
        
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(Comentarform, self).form_valid(form)
        
        
class Editarcomentarioform(forms.ModelForm):
    
    class Meta:
        model = models.Comentario
        fields = ["texto","post"]
        
        

project/Cliente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView,UpdateView
from django.contrib.auth.forms import AuthenticationForm, UserModel
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import forms, models


# Create your views here.

def view_Cliente(request): 
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url=None
    
    usuarios = UsuarioListView().get_queryset()
    return render(request, "Cliente/index.html", context={"Usuarios" : usuarios, "avatar_url" : avatar_url})




class UsuarioListView(ListView):
    model = UserModel
    context_object_name = "Usuarios"
    template_name = "Cliente/index.html"


def Formulario_usuarios(request):
    if request.method == "POST":
        form = forms.CrearUsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Cliente:login")
    else:
        form = forms.CrearUsuarioForm()
    return render(request, "Cliente/crear_usuario.html", {"form": form})


def view_usuario_buscado(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            form_filtro = forms.BuscarUsuarioForm()
            context = {"Form": form_filtro}
            return render(request, "Cliente/buscar_usuario.html", context)
        elif request.method == "POST":
            form = forms.BuscarUsuarioForm(request.POST)
            if form.is_valid():
                info = form.cleaned_data
                filtro_usuarios = User.objects.filter(username=info['username'])
                contexto_filtro = {"Filtro": filtro_usuarios}
                return render(request, "Cliente/mostrar_filtro_usuario.html", contexto_filtro)
            else:
                context = {"Form": form}
                return render(request, "Cliente/buscar_usuario.html", context)
    else: return redirect("Cliente:login")
        

def view_login(request):
    if request.method=="GET":
        return render(request, "Cliente/login.html", {"form":AuthenticationForm()})
    else:
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            contraseña = informacion["password"]
            modelo = authenticate(username=usuario,password=contraseña)
            login(request,modelo)
            return redirect("Cliente:Cliente")
        else:
            return render(request, "Cliente/login.html", {"form":formulario})
        
        
@login_required
def view_logout(request):
    if request.method=="GET":
        logout(request)
        return redirect("Cliente:Cliente")
    



def crear_avatar_view(request):
    if request.user.is_authenticated:
        usuario = request.user

        if request.method == "GET":
            formulario = forms.UserAvatarFormulario()
            return render(request,"Cliente/avatar.html",context={"form": formulario, "usuario": usuario})
        else:
            formulario = forms.UserAvatarFormulario(data=request.POST, files=request.FILES)
            if formulario.is_valid():
                informacion = formulario.cleaned_data
                modelo = models.Avatar(user=usuario, imagen=informacion["imagen"])
                modelo.save()
                return redirect("Cliente:Cliente")
    else: return redirect("Cliente:login")
        
        
@login_required
def editar_perfil_view(request):
    usuario = request.user
    avatar = models.Avatar.objects.filter(user=usuario).last()
    avatar_url = avatar.imagen.url if avatar is not None else ""
    if request.method == "GET":
        valores_iniciales = {"email": usuario.email, "nombre": usuario.first_name, "apellido": usuario.last_name,}
        formulario = forms.UserEditionFormulario(initial=valores_iniciales)
        return render(
            request,"Cliente/editar_usuario.html",context={"form": formulario, "usuario": usuario, "avatar_url": avatar_url})
    else:
        formulario = forms.UserEditionFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario.email = informacion["email"]
            usuario.set_password(informacion["password1"])
            usuario.first_name = informacion["nombre"]
            usuario.last_name = informacion["apellido"]
            usuario.save()
        return redirect("Cliente:Cliente")


def eliminar_comentario(request, id):
    instance = get_object_or_404(models.Comentario, id=id)
    if instance.autor != request.user:
        response = {"mensaje":"No tienes permiso para realizar esta accion (403)"}
        return render(request,"Cliente/accion_invalida.html" ,response)
    else:
        comentario_a_eliminar = models.Comentario.objects.filter(autor=request.user,id=id)
        comentario_a_eliminar.delete()
        return redirect("Producto:Producto")
    
    
    
def editar_comentario(request, id):
    instance = get_object_or_404(models.Comentario, id=id)
    if instance.autor != request.user:
        response = {"mensaje":"No tienes permiso para realizar esta accion (403)"}
        return render(request,"Cliente/accion_invalida.html" ,response)
    else:
        return redirect("Cliente:editarcomentario",id)
        
        
        
class ComentarioUpdateView(LoginRequiredMixin, UpdateView):
        model = models.Comentario
        template_name = "Cliente/editar_comentario.html"
        form_class = forms.Editarcomentarioform
        success_url = reverse_lazy("Producto:Producto")
        

project/Cliente/templates/Cliente/accion_invalida.html
{% extends 'Producto/index.html' %}

{% block contenido %}
    <h2>{{mensaje}}</h2>
    <div>
        <p><a class="btn btn-primary" style="background-color: #3498db;" href="{% url 'Producto:Producto' %}">Volver a videos</a></p>
    </div>
{% endblock contenido %}

project/Cliente/templates/Cliente/avatar.html
{% extends 'Cliente/index.html' %}

{% block contenido_titulo %}
    Crear Avatar
{% endblock contenido_titulo %}


{% block contenido %}
<style>
    body {
        background-color: #fbf7f7;
        color: #fff;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #f9fafb;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #252525;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.328);
    }

    label {
        display: block;
        margin-bottom: 8px;
        color: #f5f5f6;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 8px;
        margin-bottom: 15px;
        box-sizing: border-box;
        background-color: #444;
        border: 1px solid #3498db;
        border-radius: 4px;
        color: #fff;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #258cd1;
    }
</style>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

</body></p>
{% endblock contenido %}

project/Cliente/templates/Cliente/buscar_usuario.html
{% extends 'Cliente/index.html' %}

{% block contenido_titulo %}
    Busqueda de usuario
{% endblock contenido_titulo %}







{% block contenido %}
<style>
    body {
        background-color: #000;
        color: #fff;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #f9fbfc;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #333;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }

    label {
        display: block;
        margin-bottom: 8px;
        color: #fbfcfc;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 8px;
        margin-bottom: 15px;
        box-sizing: border-box;
        background-color: #444;
        border: 1px solid #3498db;
        border-radius: 4px;
        color: #fff;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #258cd1;
    }
</style>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ Form.as_p }}
    <button type="submit">Filtrar</button>
</form>

</body>
</html>
{% endblock contenido %}

    

project/Cliente/templates/Cliente/crear_usuario.html
{% extends 'MainM/base.html' %}

{% block contenido %}  
        <style>
            body {
                background-color: #fbf7f7;
                color: #fff;
                font-family: 'Arial', sans-serif;
            }

            h1 {
                color: #3498db;
            }

            form {
                max-width: 400px;
                margin: 0 auto;
                background-color: #252525;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.328);
            }

            label {
                display: block;
                margin-bottom: 8px;
                color: #3498db;
            }

            input[type="text"],
            input[type="password"] {
                width: 100%;
                padding: 8px;
                margin-bottom: 15px;
                box-sizing: border-box;
                background-color: #444;
                border: 1px solid #3498db;
                border-radius: 4px;
                color: #fff;
            }

            button {
                background-color: #3498db;
                color: #fff;
                padding: 10px 15px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            button:hover {
                background-color: #258cd1;
            }
        </style>
    <body>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Guardar</button>
            </form>

    </body></p>

{% endblock contenido %}

project/Cliente/templates/Cliente/editar_comentario.html
{% extends 'MainM/base.html' %}

{% block contenido_titulo %}
    Editar Comentario
{% endblock contenido_titulo %}


{% block contenido %} 
        <style>
            body {
                background-color: #fbf7f7;
                color: #fff;
                font-family: 'Arial', sans-serif;
            }

            h1 {
                color: #f9fafb;
            }

            form {
                max-width: 400px;
                margin: 0 auto;
                background-color: #252525;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.328);
            }

            label {
                display: block;
                margin-bottom: 8px;
                color: #f8f8f8;
            }

            input[type="text"],
            input[type="password"] {
                width: 100%;
                padding: 8px;
                margin-bottom: 15px;
                box-sizing: border-box;
                background-color: #444;
                border: 1px solid #3498db;
                border-radius: 4px;
                color: #fff;
            }

            button {
                background-color: #3498db;
                color: #fff;
                padding: 10px 15px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            button:hover {
                background-color: #258cd1;
            }
        </style>
    <body>
            <form action="{% url 'Cliente:editarcomentario' comentario.pk %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Editar</button>
            </form>

    </body></p>

{% endblock contenido %}

project/Cliente/templates/Cliente/editar_usuario.html
{% extends 'Cliente/index.html' %}

{% block contenido_titulo %}
    Editar Usuario
{% endblock contenido_titulo %}


{% block contenido %} 
        <style>
            body {
                background-color: #fbf7f7;
                color: #fff;
                font-family: 'Arial', sans-serif;
            }

            h1 {
                color: #f9fafb;
            }

            form {
                max-width: 400px;
                margin: 0 auto;
                background-color: #252525;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.328);
            }

            label {
                display: block;
                margin-bottom: 8px;
                color: #f8f8f8;
            }

            input[type="text"],
            input[type="password"] {
                width: 100%;
                padding: 8px;
                margin-bottom: 15px;
                box-sizing: border-box;
                background-color: #444;
                border: 1px solid #3498db;
                border-radius: 4px;
                color: #fff;
            }

            button {
                background-color: #3498db;
                color: #fff;
                padding: 10px 15px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            button:hover {
                background-color: #258cd1;
            }
        </style>
    <body>
        <p><a class="btn btn-primary" style="background-color: #3498db;" href="{% url 'Cliente:avatar' %}">Crear Avatar</a></p>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Guardar</button>
            </form>
            <p>ACLARACIÓN, no se como sacar esto: 
                "Contraseña:
                No se ha establecido la clave.
                Las contraseñas no se almacenan en bruto, así que no hay manera de ver la contraseña del usuario, pero se puede cambiar la contraseña mediante este formulario.
                Por ese motivo queria aclarar que ese hipervinculo no funciona"</p>
    </body></p>

{% endblock contenido %}

project/Cliente/templates/Cliente/index.html
{% extends 'MainM/base.html' %}


{% block contenido_titulo %}
    Registrarse/Iniciar sesión
{% endblock contenido_titulo %}


{% block contenido %}
    <p>Si todavia no tenés perfil en el blog, registrate y comentá algo!</p>
    <div></div>
    <p><a class="btn btn-primary" style="background-color: #3498db;" href="{% url 'Cliente:crear_usuarios' %}">Registrate</a></p>
    <div></div>
    <p><h3>Miembros de la comunidad</h3></p>
    <div></div>
    <p><a class="btn btn-primary" style="background-color: #3498db;" href="{% url 'Cliente:usuario_buscado' %}">Filtro</a></p>
    {% for persona in Usuarios %}
            <div></div>
            {% if persona.username == "admin" %}
            {% else %}
                <p>Usuario: {{persona.username}}</p>
            {% endif %}
            
    {% endfor %}
{% endblock contenido %}

project/Cliente/templates/Cliente/login.html
{% extends 'MainM/base.html' %}

{% block contenido_titulo %}
    Inicio de Sesion
{% endblock contenido_titulo %}

{% block contenido %}  

        <style>
            body {
                background-color: #fbf7f7;
                color: #fff;
                font-family: 'Arial', sans-serif;
            }

            h1 {
                color: #fafbfc;
            }

            form {
                max-width: 400px;
                margin: 0 auto;
                background-color: #252525;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.328);
            }

            label {
                display: block;
                margin-bottom: 8px;
                color: #fdfefe;
            }

            input[type="text"],
            input[type="password"] {
                width: 100%;
                padding: 8px;
                margin-bottom: 15px;
                box-sizing: border-box;
                background-color: #444;
                border: 1px solid #3498db;
                border-radius: 4px;
                color: #fff;
            }

            button {
                background-color: #3498db;
                color: #fff;
                padding: 10px 15px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            button:hover {
                background-color: #258cd1;
            }
        </style>
    </head>
    <body>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Iniciar Sesion</button>
            </form>

    </body></p>

{% endblock contenido %}

project/Cliente/templates/Cliente/mostrar_filtro_usuario.html
{% extends 'Cliente/index.html' %}

{% block contenido_titulo %}
    Filtro Usuario + Vista detallada
{% endblock contenido_titulo %}

{% block contenido %}

<style>
    body {
        background-color: #000;
        color: #fff;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #f7f9fb;
    }

    .user-list {
        list-style: none;
        padding: 0;
    }

    .user-item {
        background-color: #333;
        padding: 10px;
        margin: 10px 0;
        border-radius: 4px;
    }

    .btn-back {
        background-color: #3498db;
        color: #fff;
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 4px;
        display: inline-block;
        margin-top: 20px;
    }

    .btn-back:hover {
        background-color: #258cd1;
    }
</style>
</head>
<body>

<ul class="user-list">
    {% for persona in Filtro %}
        <li class="user-item">Nombre: {{ persona.first_name }} || Apellido: {{ persona.last_name}} || Usuario: {{persona.username}} || Email: {{persona.email}}</li>
    {% endfor %}
</ul>

<p><a class="btn btn-back" href="{% url 'Cliente:Cliente' %}">Volver</a></p>

</body>

{% endblock contenido %}

project/Cliente/templates/Cliente/navbar.html
<!-- Responsive navbar-->
{% load static %}
<style>
    .avatar-container {
        margin-top: 0px;
    }

    .avatar-img {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        border: 2px solid #3498db;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.5);
    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Put*tube</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'MainM:MainM' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Producto:Producto' %}">Videos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'MainM:Redes' %}">Redes Sociales</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Cliente:Cliente' %}">Registrarse</a></li>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'Cliente:editarusuario' %}">Editar Usuario: {{ user.username }}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Cliente:logout' %}">Cerrar Sesion</a></li>
                        {% if avatar_url %}
                            <li class="nav-item avatar-container">
                                <img src="{{ avatar_url }}" alt="Avatar" class="avatar-img"/>
                            </li>
                        {% else %}
                            <!-- Si no hay avatar, muestra una imagen predeterminada -->
                            <li class="nav-item avatar-container">
                                <img src="{% static 'MainM/img/avatar_predeterminado.webp' %}" alt="Avatar" class="avatar-img"/>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'Cliente:login' %}">Iniciar Sesion</a></li>
                    {% endif %}
                </ul>
            </ul>
        </div>
    </div>
</nav>