project/Cliente/urls.py
from django.urls import path
from . import views



app_name = "Cliente"

urlpatterns = [
    path("", views.view_Cliente, name = "Cliente"),
    path("usuario_buscado/", views.view_usuario_buscado, name="usuario_buscado"),
    path("crear_usuarios/", views.Formulario_usuarios, name="crear_usuarios"),
    path("mostrar_usuario_filtrado/", views.view_usuario_buscado, name="filtro_usuario"),
    path("login/", views.view_login, name="login"),
    path("logout/", views.view_logout, name="logout"),
    path("avatar/", views.crear_avatar_view, name="avatar"),
    path("editar_usuario/", views.editar_perfil_view, name="editarusuario"),
    path("eliminar_comentario/<id>", views.eliminar_comentario,name="borrarcomentario"),
    path("editar_comentario/<pk>", views.ComentarioUpdateView.as_view(), name="editarcomentario"),
    path("eleccion_comentario/<id>", views.editar_comentario, name="eleccioncomentario"),
]

project/MainM/urls.py
from django.urls import path
from . import views

app_name = "MainM"

urlpatterns = [
    path("", views.view_mainmenu, name = "MainM"),
    path("Redes/", views.view_about, name = "Redes"),
]

project/Producto/urls.py
from django.urls import path
from . import views

app_name = "Producto"

urlpatterns = [
    path("", views.view_Producto, name = "Producto"),
    path("comentar/", views.comentar_view, name="comentar"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("MainM.urls")),
    path("Cliente/", include("Cliente.urls")),
    path("Producto/", include("Producto.urls")),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/Cliente/models.py
from django.db import models
from django.contrib.auth.models import User

 

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(default="avatares/avatar_predeterminado.webp", upload_to='avatares/', null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"


class Videos(models.Model):
    video = models.FileField(upload_to="videos/", null=True, blank=True)
    titulo = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.titulo}"


class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.CharField(max_length=2200)
    post = models.ForeignKey(Videos, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.autor}: '{self.post}'"

project/Producto/models.py
from django.db import models

# Create your models here.

project/Producto/forms.py
from django import forms
from . import models

project/Producto/views.py
from django.shortcuts import render, redirect
from . import forms, models
from Cliente import models
from django.contrib.auth.decorators import login_required
from Cliente import forms
# Create your views here.

def view_Producto(request):
    todos_los_videos = models.Videos.objects.all()
    todos_los_comentarios = models.Comentario.objects.all()
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
        
    else:
        avatar_url=None
    
    return render(request, "Producto/index.html", context= {"avatar_url":avatar_url,"videos": todos_los_videos,"comentarios":todos_los_comentarios})




def comentar_view(request):
    
    usuario = request.user

    if request.method == "GET":
        formulario = forms.Comentarform()
        return render(request,"Producto/comentarios.html",context={"form": formulario, "usuario": usuario})
    else:
        formulario = forms.Comentarform(data=request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            modelo = models.Comentario(autor=usuario, post=informacion["post"], texto=informacion["texto"])
            modelo.save()
            return redirect("Producto:Producto")

    

project/Producto/templates/Producto/comentarios.html
{% extends 'Producto/index.html' %}




{% block contenido_titulo %}
    Comentá! (solo posible si tienes un usuario creado)
{% endblock contenido_titulo %}

{% block contenido %}
<style>
    body {
        background-color: #000;
        color: #fff;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #f9fafb;
    }

    form {
        max-width: 400px;
        margin: 20px auto;
        background-color: #333;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }

    label {
        display: block;
        margin-bottom: 8px;
        color: #fcfefe;
    }

    textarea {
        width: 100%;
        padding: 8px;
        margin-bottom: 15px;
        box-sizing: border-box;
        background-color: #444;
        border: 1px solid #3498db;
        border-radius: 4px;
        color: #fff;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #258cd1;
    }

    .btn-back {
        background-color: #3498db;
        color: #fff;
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 4px;
        display: inline-block;
        margin-top: 20px;
    }

    .btn-back:hover {
        background-color: #258cd1;
    }
</style>
</head>
<body>
{% if user.is_authenticated %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Comentar</button></p>
</form>

<a class="btn btn-back" href="{% url 'Producto:Producto' %}">Volver a videos</a>

</body>
{% else %}
    <p><a class="btn btn-back" href="{% url 'Cliente:login' %}">Primero hacé login</a></p>
{% endif %}
{% endblock contenido %}

project/Producto/templates/Producto/index.html
{% extends 'MainM/base.html' %}

<style>
    .card {
        background-color: rgb(42, 40, 40);
        color: #fff;
    }

    .card-body {
        padding: 20px;
    }

    .video-container {
        position: relative;
        overflow: hidden;
        padding-top: 56.25%; /* Aspect ratio 16:9 */
    }

    .video-container iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    /* Para que las tarjetas estén alineadas horizontalmente en pantallas más grandes */
    @media (min-width: 768px) {
        .card {
            margin-bottom: 0;
        }
    }
</style>

{% block contenido_titulo %}
    Videos
{% endblock contenido_titulo %}

{% block contenido %}
    <h5>Acá compartimos con ustedes nuestras aventuras!</h5>

    <style>
        .video-container {
            background-color: rgb(42, 40, 40);
            padding: 10px; 
            border-radius: 20px; 
            margin-bottom: 20px;
            max-width: 300px; 
            margin: auto;
            text-align: center;
            align-items: center; 
        }
    
        .comentario-container {
            background-color: rgb(42, 40, 40);
            padding: 10px; 
            border-radius: 20px; 
            margin-bottom: 20px;
            max-width: 300px; 
            margin: auto;
            text-align: left; 
        }
    
        .comentario {
            color: #fff; 
        }

        .contenedor-principal {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around; 
    }

    .eliminar-btn {
        background-color: #FF5733;
        color: white;
        padding: 8px 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .editar-btn {
        background-color: #3498db;
        color: white;
        padding: 8px 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    </style>
    
    {% for vid in videos %}
        <div class="video-container">
            <h4>{{ vid.titulo }}</h4>
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card-body">
                        <div class="video-container">
                            <video src="{{ vid.video.url }}" type="video/mp4" controls allowfullscreen="" frameborder="0" style="width: 450%;"></video>
                        </div>
                    </div>
                </div>
    
                <!-- Mostrar comentarios para el video actual -->
                {% for comentario in vid.comentario_set.all %}
                    <div class="comentario-container">
                        <p class="comentario">{{ comentario.autor }}: {{ comentario.texto }}</p>
                    <button class="eliminar-btn">
                        <a href="{% url 'Cliente:borrarcomentario' comentario.id %}" style="color: white;">Eliminar</a>
                    </button>
                    <button class="editar-btn">
                        <a href="{% url 'Cliente:eleccioncomentario' comentario.id %}" style="color: white;">Editar</a>
                    </button>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

        <p><a class="btn btn-primary" style="background-color: #3498db;" href="{% url 'Producto:comentar' %}">Comentar</a></p>
        <div></div>


{% endblock contenido %}

project/Producto/templates/Producto/tarjeta_videos.html
{% load static %}
<div>
<p><head>
    <style>
        .card {
            background-color: rgb(42, 40, 40);
            color: #fff;
        }

        .card-body {
            padding: 20px;
        }

        .video-container {
            position: relative;
            overflow: hidden;
            padding-top: 56.25%; /* Aspect ratio 16:9 */
        }

        .video-container iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        /* Para que las tarjetas estén alineadas horizontalmente en pantallas más grandes */
        @media (min-width: 768px) {
            .card {
                margin-bottom: 0;
            }
        }
    </style>
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="video-container">
                        <iframe src="{{vid.video.url}}" allowfullscreen="" frameborder="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
        <!-- Agrega más tarjetas aquí según sea necesario -->
    </div>
</div>
</body></p>
</div>

project/Producto/templates/Producto/ver_comentarios.html
{% block contenido %}
<style>
    body {
        background-color: #000;
        color: #fff;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #f5f7f8;
    }

    h4 {
        color: #f6f8f9;
        margin-bottom: 5px;
    }

    p {
        color: #fff;
        margin-bottom: 15px;
    }
</style>
</head>
<body>

{% for persona in Autor %}
    <h4>{{ persona.autor }}</h4>
    <p>{{ persona.comentario }}</p>
{% endfor %}

</body>
</html>
{% endblock contenido %}

    